# Generated by Django 5.1.4 on 2024-12-17 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theatrehall",
            name="rows",
            field=models.IntegerField(
                default=10, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="theatrehall",
            name="seats_in_row",
            field=models.IntegerField(
                default=10, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
