# Generated by Django 5.1.4 on 2024-12-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_ticket_performance_alter_ticket_reservation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("row", "seat")},
        ),
    ]
