# Generated by Django 5.1.4 on 2024-12-14 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_actor_first_name_alter_actor_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="reservation",
        ),
        migrations.AddField(
            model_name="reservation",
            name="ticket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="core.ticket",
            ),
        ),
    ]
