# Generated by Django 5.1.4 on 2024-12-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_ticket_reservation_reservation_ticket"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("user", "ticket")},
        ),
    ]
