# Generated by Django 5.1.4 on 2024-12-15 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_reservation_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="ticket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="core.ticket",
            ),
        ),
    ]
